import argparse
import Program_2


if __name__ == '__main__':
	parser = argparse.ArgumentParser()
	parser.add_argument("path", help="a path to the csv file generated by the first program")
	args = parser.parse_args()
	try:
		Program_2.work_with_format_csv(args.path)
		print('Completed successfully')
	except BaseException as error:
		print(error)
		print('Error occured')